### ISSUE TITLE
more data: note differences in data

### ISSUE THREAD

**Issue by fsolt** [fsolt/dcpo_dem_mood#6]
Due to revisions to the underlying datasets (and, possibly, transcription errors), we were not able to perfectly replicate the set of survey data summarized in the article's Dataverse file:

- [x] [Four unavailable country-year surveys](https://github.com/fsolt/dcpo_dem_mood/issues/5#issue-637892464): South Sudan arabb4; Dominican Rep lb 2003; Spain lb 2005; Bahrain wvs 2014

- [x] [Many differences in sample size](https://github.com/fsolt/DCPOtools/issues/28#issuecomment-644978165) and number of respondents answering supportively, not fully explained by treatment of non-responses

- [x] Many additional surveys (plus 427 obs; with with_min_yrs(2) accounted, over 20% more country-years and over 20% more country-year-items)

**Comment by fsolt** [comment]
Cite to [Grossman (2020, 1)](https://doi.org/10.1017/S1537592720001206) re the distinction between primary and secondary replications (the article's Dataverse materials allow a secondary replication; we could not entirely achieve a primary replication).

**Comment by fsolt** [comment]
Should go in appendix

**Comment by sammo3182** [comment]
One possible reason of the variance in the point estimation, ref. issue #15

**Comment by fsolt** [comment]
> One possible reason of the variance in the point estimation, ref. issue #15

I don't buy it even for a second; we replicate the results fine when we don't include measurement error.  It should have gotten into the appendix, though, and it didn't, so we'll have to put it in now.

**Comment by fsolt** [comment]
Maybe have to add note about APSR V-Dem data here, too, if we can't figure out how the standardization was performed.

**Comment by casstai** [comment]
@fsolt @sammo3182  I just doubt-checked the models we used in our first version manuscript. Model 1 is Claassen's point estimate [checked], and model 3 is DCPO measures with more data [checked].  Still, the tricky part is Model2.  In model 2, we replicate claassen's theta by using corrected and expanded data because claassen_replication_input data includes year 2020. And then,   we merged Claassen's model5 theta created by claassen_replication_input data with his original control variables [checked, the final version for our first manucript[81c6ef0](https://github.com/fsolt/dcpo_dem_mood/commit/81c6ef0cb2b8468d92be01f485f622fd78f945f4)]. In this way, we get corrected data with the same-year of Claassen's data. 
My question is whether the data for the previous Model2 is the data we will use in Model2 for our new version.  Does it mean the untruncated Claassen's model5 theta is the data we want to use in Model 3 for our new version?
Or, the corrected but with same country-year data means theta should be estimated by using the corrected but with same country-year data, for example, excluding year 2019 and 2020?

**Comment by fsolt** [comment]
The appropriate public opinion estimates to use for Model 2 are those now on OSF called claassen_m5_3k_05-05-11-16.rda: they are all the same country-years (minus 4 that don't exist), drawn straight from all the surveys, processed by DCPOtools.

Model 3 is estimates on the expanded dataset (e.g., including years 2019 and 2020).  Still not sure if we actually have that yet.

**Comment by casstai** [comment]
Gotcha.  I see claassen_m5_3k_05-05-11-16.rda on osf.  It seems Model3 is our original claassen_m5_theta.rda using expanded data (including 2019 and 2020).

**Comment by Tyhcass** [comment]
@fsolt  the extracted theta from claassen_m5_3k_05-05-11-16.rda has 30 (year)*136(country), however, in Claassen's original data, country-year is 30*137.  Any idea which country is missing during the correction process?

**Comment by casstai** [comment]
@sammo3182 please check https://osf.io/tnp2a/  correct_cls_ajps.rda and correct_cls_apsr.rda. Those two are created by  claassen_m5_3k_05-05-11-16.rda and claassen_replication.rds (input for replicating claassen's theta ).  You should not need to change anything on your codes, just  update the dataset in your analysis codes. 
@fsolt If I am right, claassen_replication.rds is our corrected input data since this one is different from Claassen's pure and expanded data.   The theta from claassen_m5_3k_05-05-11-16 has 136 countries but theta from pure and expanded data has 137 countries.  Also, I am wrong and we don't have data for Model3. 

- [x] Differences between pure data and corrected data, identifying this "missing country".

**Comment by fsolt** [comment]
> The theta from claassen_m5_3k_05-05-11-16 has 136 countries but theta from pure and expanded data has 137 countries.

Good catch: it's Bahrain again.  I'll get that fixed and a new version out on OSF.

> I am wrong and we don't have data for Model3.

That I knew.  exp_claassen_m5_3k_07-23-10-50.rda is demsupport estimates for Model 3: based on all available data, direct from the surveys and processed via DCPOtools (and so correct), and run through Claassen's Model 5.  It's on OSF now

**Comment by casstai** [comment]
The expanded and corrected data is on OSF. All variable names have been converted to names in models.  At least at my end, everything runs well in MOC models.  @sammo3182 update dataset and then just run it. It should be no pain at all. 
So, we are waiting for the new version of the corrected data, is that right? 
So, with the corrected data of 136 countries and the expanded and corrected data, no significant and smaller magnitude in moc. 
Also, regarding substantive discussion, I think the main point of R3's articles is also current support measures are not accurate because of ignoring cultural bounds. I am not clear about how to discuss more on "substantive findings" on support and regime survival. Please let me know if you have any ideas on that.

**Comment by fsolt** [comment]
Okay, claassen_m5_3k_07-25-09-50.rda is on OSF for our Model 2—with 137 countries, all the same country-years (minus 4 that don't exist), drawn straight from all the surveys, processed by DCPOtools, and run through Claassen's Model 5.

**Comment by casstai** [comment]
> Okay, claassen_m5_3k_07-25-09-50.rda is on OSF for our Model 2—with 137 countries, all the same country-years (minus 4 that don't exist), drawn straight from all the surveys, processed by DCPOtools, and run through Claassen's Model 5.

En, the structure of claassen_m5_theta is 1000*31*137. The number of countries is correct, but now the max year is 2018. I checked the file "Claassen_replication_input" which was pushed two days ago, the year of 2018 is from Colombia.

**Comment by casstai** [comment]
I added a little detail on the differences between corrected data and original data, and between standardized values. 
However, I didn't figure out all 5 "missing country-year“observations mentioned in [c2f5ea3](https://github.com/fsolt/dcpo_dem_mood/commit/c2f5ea31ebd89ed1af6cf9c47bad0b8b740fecc2) and what the result of line 193 referred to.  @fsolt

**Comment by sammo3182** [comment]
Moving to a separate project in [fsolt/dem_mood](https://github.com/fsolt/dem_mood)
